### ISSUE TITLE
Erro no consumo de JSON na entidade Promocao

### ISSUE THREAD

**Issue by AdrianoModa** [michael-alb/akicupom-backend#2]
Quando entro com json para atualizar, todos os atributos alteram, porém o atributo categoria que é de outra entidade relacionada a Promocao, não altera. @michael-alb  @jordanmoreira

**Comment by michael-alb** [comment]
Adriano, por favor, pode detalhar mais, não entendi.

**Comment by jordanmoreira** [comment]
eita mah, n entendi muita coisa tbm n kkk

**Comment by AdrianoModa** [comment]
Quando envio **dados** pelo Navegador via URL para **Atualizar** (@PUT) ele funciona e atualiza todos os atributos normalmente.
Mas quando envio dados como JSON para **Atualizar** (@PUT ) na entidade **Promocao** todos os atributos atualizam exceto o atributo categoria.

**Comment by AdrianoModa** [comment]
Acredito que no Front-end vamos precisar de envio via JSON para o banco. Mas na aula de hoje 26/09 explico melhor esse erro.
